Repository DisasterKok/Disaterkok_frontend, pull requests merged in 2023-11, with the labels that each got.

#24 제보 - 제보 게시글 카드 컴포넌트 제작
  src/components/ReportArticle/ReportArticleCard.tsx
  src/components/ReportArticle/types.ts
  src/components/SelectRegion/SigunguTable.tsx
  src/constants/DummyArticle.ts
  src/constants/colors.js
  src/pages/Report.tsx
Labels: 🎨 Html&css, ✨ Feature

#20 제보 - 지역,재난 필터 모달
  App.tsx
  src/apis/.gitkeep
  src/apis/fetchRegionAPI/fetchEupmyeondong.tsx
  src/apis/fetchRegionAPI/fetchSidoInfo.tsx
  src/apis/fetchRegionAPI/fetchSigunguInfo.tsx
  src/components/BottomSheetModal/SelectDisasterBottomSheet.tsx
  src/components/BottomSheetModal/SelectRegionBottomSheet.tsx
  src/components/BottomSheetModal/index.js
  src/components/ReportArticle/ReportArticleCard.tsx
  src/components/ReportArticle/types.ts
  src/components/SelectDisaster/MainCategory.tsx
  src/components/SelectDisaster/SubCategory.tsx
  src/components/SelectDisaster/types.ts
  src/components/SelectRegion/EupmyeondongTable.tsx
  src/components/SelectRegion/SidoTable.tsx
  src/components/SelectRegion/SigunguTable.tsx
  src/components/SelectRegion/index.js
  src/components/SelectRegion/types.ts
  src/constants/DummyArticle.ts
  src/constants/DummyDisaster.ts
  src/constants/colors.js
  src/pages/DisasterNotiSettings.tsx
  src/pages/Report.tsx
Labels: 🎨 Html&css, ✨ Feature

#28 제보 - 상세페이지, 작성페이지 UI
  App.tsx
  src/components/ReportArticle/ReportArticleCard.tsx
  src/components/ReportArticle/types.ts
  src/constants/DummyArticle.ts
  src/pages/Report.tsx
  src/pages/ReportArticleDetail.tsx
  src/pages/ReportPost.tsx
  src/pages/index.js
Labels: 🎨 Html&css, ✨ Feature

#31 홈 - 우리동네 설정 Bottom Sheet UI
  src/components/Home/AddressSetting/AddAdress.tsx
  src/components/Home/AddressSetting/AddressBottomSheet.tsx
  src/components/Home/AddressSetting/DeleteConfirmModal.tsx
  src/components/Home/AddressSetting/TownList.tsx
  src/components/Home/IssueSection.tsx
  src/components/Home/SwitchButton.tsx
  src/components/Home/WeatherSection.tsx
  src/components/SelectAddress/AliasPostcode.tsx
  src/pages/Home.tsx
  src/pages/SelectLocation.tsx
Labels: 🎨 Html&css, ✨ Feature

#34 회원가입 api 연결 설정
  App.tsx
  android/app/build.gradle
  env.d.ts
  ios/disaterkok_frontend/Info.plist
  package-lock.json
  package.json
  src/apis/userAPI.ts
  src/config/api.ts
  src/pages/SetName.tsx
  src/pages/SignUp.tsx
Labels: 📬 API, ✨ Feature

#40 알림 화면 UI
  src/components/BottomSheetModal/NotiContentBottomSheet.tsx
  src/components/BottomSheetModal/index.js
  src/components/Home/ReportSection.tsx
  src/constants/colors.js
  src/navigation/HomeStack.tsx
  src/navigation/types.ts
  src/pages/Home.tsx
  src/pages/Setting.tsx
  src/pages/index.js
Labels: 🎨 Html&css, ✨ Feature

#37 우리동네 선택 바텀모달, 공유하기 모달 제작
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/BottomSheetModal/NotiContentBottomSheet.tsx
  src/components/BottomSheetModal/SelectDisasterBottomSheet.tsx
  src/components/BottomSheetModal/SelectRegionBottomSheet.tsx
  src/components/BottomSheetModal/index.js
  src/components/ClipBoard/ClipBoard.tsx
  src/components/Home/AddressSetting/AddressBottomSheet.tsx
  src/components/Home/AddressSetting/TownList.tsx
  src/components/Home/ReportSection.tsx
  src/components/ReportArticle/ReportArticleCard.tsx
  src/components/ReportArticle/ReportArticleList.tsx
  src/components/ReportArticle/SharedModal.tsx
  src/constants/colors.js
  src/navigation/HomeStack.tsx
  src/navigation/types.ts
  src/pages/Home.tsx
  src/pages/ReportArticleDetail.tsx
  src/pages/ReportList.tsx
  src/pages/Setting.tsx
  src/pages/index.js
Labels: 🎨 Html&css, ✨ Feature, 🔨 Refactor

#43 AppBar 및 검색페이지 추가
  App.tsx
  src/components/Home/AppBar.tsx
  src/components/Home/WeatherSection.tsx
  src/components/Search/KeywordsList.tsx
  src/components/Search/SearchBar.tsx
  src/constants/colors.js
  src/navigation/HomeStack.tsx
  src/navigation/types.ts
  src/pages/Home.tsx
  src/pages/Search.tsx
Labels: 🎨 Html&css, ✨ Feature

#44 검색페이지 - 검색 결과 UI 추가
  src/components/Home/ReportSection.tsx
  src/components/Search/ReportListPreview.tsx
  src/components/Search/SearchResult.tsx
  src/components/Search/SolutionListPreview.tsx
  src/components/common/ReportArticle/ReportArticleCard/ReportArticleCard.tsx
  src/components/common/ReportArticle/ReportArticleList/ReportArticleList.tsx
  src/components/common/TabBar/TabBar.tsx
  src/hooks/useTabBar.tsx
  src/screens/ReportList.tsx
  src/screens/Search.tsx
Labels: 🎨 Html&css, ✨ Feature
